version: '2.3'

x-environment:
  &default-environment
    DOCKERHOST: ${DOCKERHOST:-}

services:
  ci:
    build:
      context: .
      dockerfile: govcms-ci.Dockerfile
    image: deptcms-ci
    environment:
      << : *default-environment
